package yarn

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/nubjs/nub/pm-go/internal/fsutil"
	"github.com/nubjs/nub/pm-go/internal/lockfile"
	"github.com/nubjs/nub/pm-go/internal/manifest"
)

func WriteBerry(path string, g *lockfile.Graph, project *manifest.Package) error {
	data, err := EncodeBerry(g, project)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return fsutil.WriteDefault(path, data)
}
func EncodeBerry(g *lockfile.Graph, project *manifest.Package) ([]byte, error) {
	canonical := g.CanonicalPackages()
	patches, err := lockfile.ResolvePatchValues(g.PatchedDependencies, g.Packages)
	if err != nil {
		return nil, err
	}
	extra, patchSpecs := map[string]lockfile.Set{}, map[string]string{}
	note := func(key, name, rangeText string) {
		p := canonical[key]
		if p == nil {
			return
		}
		body := rangeText
		if !berryHasProtocol(body) {
			body = "npm:" + body
		}
		spec := name + "@" + body
		if _, protocol, body, ok := parseBerrySpec(spec); ok && protocol == "patch" {
			if path, count := berryPatchPath(body); count == 1 {
				if expected, ok := patches[p.SpecKey()]; ok && expected == path {
					patchSpecs[key] = spec
				}
			}
		}
		if spec != berryExactSpec(p, patches, patchSpecs) {
			if extra[key] == nil {
				extra[key] = lockfile.Set{}
			}
			extra[key].Add(spec)
		}
	}
	for _, dep := range g.RootDeps() {
		key := lockfile.CanonicalKey(dep.DepPath)
		if canonical[key] == nil {
			continue
		}
		for _, deps := range []map[string]string{project.Dependencies, project.DevDependencies, project.OptionalDependencies, project.PeerDependencies} {
			if rangeText, ok := deps[dep.Name]; ok {
				note(key, dep.Name, rangeText)
				break
			}
		}
	}
	for _, key := range sortedKeys(canonical) {
		p := canonical[key]
		for _, name := range sortedKeys(p.DeclaredDependencies) {
			if resolved, ok := p.Dependencies[name]; ok {
				note(lockfile.ChildCanonicalKey(name, resolved), name, p.DeclaredDependencies[name])
			}
		}
	}
	type block struct{ key, text string }
	rootKey, rootBlock := berryRootBlock(project)
	blocks := []block{{rootKey, rootBlock}}
	for _, key := range sortedKeys(canonical) {
		p := canonical[key]
		exact := berryExactSpec(p, patches, patchSpecs)
		specs := extra[key].Sorted()
		if len(specs) == 0 {
			specs = []string{exact}
		}
		var out strings.Builder
		fmt.Fprintf(&out, "%s:\n  version: %s\n  resolution: %s\n", berryQuote(strings.Join(specs, ", ")), p.Version, berryQuote(exact))
		berryWriteDeps(&out, "dependencies", p.Dependencies, p.DeclaredDependencies, canonical, patches, patchSpecs)
		berryWriteDeps(&out, "optionalDependencies", p.OptionalDependencies, p.DeclaredDependencies, canonical, patches, patchSpecs)
		berryWritePlainMap(&out, "peerDependencies", p.PeerDependencies)
		if len(p.PeerDependenciesMeta) != 0 {
			out.WriteString("  peerDependenciesMeta:\n")
			for _, name := range sortedKeys(p.PeerDependenciesMeta) {
				fmt.Fprintf(&out, "    %s:\n      optional: %t\n", berryQuoteIfNeeded(name), p.PeerDependenciesMeta[name].Optional)
			}
		}
		bins := maps.Clone(p.Bin)
		delete(bins, "")
		berryWritePlainMap(&out, "bin", bins)
		if p.YarnChecksum != nil {
			fmt.Fprintf(&out, "  checksum: %s\n", *p.YarnChecksum)
		}
		link := "hard"
		if p.Source != nil && (p.Source.Kind == lockfile.Link || p.Source.Kind == lockfile.Portal) {
			link = "soft"
		}
		fmt.Fprintf(&out, "  languageName: node\n  linkType: %s\n", link)
		blocks = append(blocks, block{specs[0], out.String()})
	}
	slices.SortStableFunc(blocks, func(a, b block) int { return strings.Compare(a.key, b.key) })
	var out strings.Builder
	out.WriteString("# This file is generated by running \"yarn install\" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: 10\n  cacheKey: 10c0\n\n")
	for i, b := range blocks {
		if i != 0 {
			out.WriteByte('\n')
		}
		out.WriteString(b.text)
	}
	return []byte(out.String()), nil
}
func berryExactSpec(p *lockfile.Package, patches, patchSpecs map[string]string) string {
	if p.Source != nil {
		return p.Name + "@" + p.Source.Specifier()
	}
	if path, ok := patches[p.SpecKey()]; ok {
		if spec, ok := patchSpecs[p.SpecKey()]; ok {
			return spec
		}
		return p.Name + "@patch:" + p.Name + "@npm%3A" + p.Version + "#" + path
	}
	return p.Name + "@npm:" + p.Version
}
func berryWriteDeps(out *strings.Builder, section string, deps, declared map[string]string, canonical map[string]*lockfile.Package, patches, patchSpecs map[string]string) {
	values := map[string]string{}
	for _, name := range sortedKeys(deps) {
		value := deps[name]
		target := canonical[lockfile.ChildCanonicalKey(name, value)]
		if target == nil {
			continue
		}
		body := ""
		if target.Source != nil {
			body = target.Source.Specifier()
		} else {
			var ok bool
			body, ok = declared[name]
			if !ok {
				if _, patched := patches[target.SpecKey()]; patched {
					body = strings.TrimPrefix(berryExactSpec(target, patches, patchSpecs), name+"@")
				} else {
					body = lockfile.DependencyVersion(name, value)
				}
			}
			if !strings.Contains(body, ":") {
				body = "npm:" + body
			}
		}
		values[name] = body
	}
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(out, "  %s:\n", section)
	for _, name := range sortedKeys(values) {
		fmt.Fprintf(out, "    %s: %s\n", berryQuoteIfNeeded(name), berryQuote(values[name]))
	}
}
func berryWritePlainMap(out *strings.Builder, section string, values map[string]string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(out, "  %s:\n", section)
	for _, name := range sortedKeys(values) {
		fmt.Fprintf(out, "    %s: %s\n", berryQuoteIfNeeded(name), berryQuoteIfNeeded(values[name]))
	}
}
func berryQuote(s string) string {
	return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(s) + "\""
}
func berryQuoteIfNeeded(s string) string {
	if s == "" || strings.ContainsRune("@*&?|>%`!#-[]{},\"' ", rune(s[0])) || strings.HasSuffix(s, " ") || strings.Contains(s, ":") || strings.Contains(s, " #") {
		return berryQuote(s)
	}
	return s
}
func berryRootBlock(project *manifest.Package) (string, string) {
	name := "root"
	if project.Name != nil {
		name = *project.Name
	}
	header := name + "@workspace:."
	var out strings.Builder
	fmt.Fprintf(&out, "%s:\n  version: 0.0.0-use.local\n  resolution: %s\n", berryQuote(header), berryQuote(header))
	deps := maps.Clone(project.Dependencies)
	if deps == nil {
		deps = map[string]string{}
	}
	maps.Copy(deps, project.DevDependencies)
	for i, values := range []map[string]string{deps, project.OptionalDependencies} {
		if len(values) == 0 {
			continue
		}
		section := "dependencies"
		if i == 1 {
			section = "optionalDependencies"
		}
		fmt.Fprintf(&out, "  %s:\n", section)
		for _, name := range sortedKeys(values) {
			body := values[name]
			if !berryHasProtocol(body) {
				body = "npm:" + body
			}
			fmt.Fprintf(&out, "    %s: %s\n", berryQuoteIfNeeded(name), berryQuote(body))
		}
	}
	out.WriteString("  languageName: unknown\n  linkType: soft\n")
	return header, out.String()
}
