package yarn

import (
	"github.com/nubjs/nub/pm-go/internal/lockfile"
	"github.com/nubjs/nub/pm-go/internal/manifest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBerryWriterLayoutAndMetadata(t *testing.T) {
	pj, _ := manifest.ParsePackage([]byte(`{"name":"project","dependencies":{"foo":"^1"},"devDependencies":{"foo":"~1"}}`))
	g := lockfile.NewGraph()
	p := lockfile.NewPackage("foo", "1.2.0")
	p.YarnChecksum = new("10c0/abc")
	p.PeerDependencies = map[string]string{"@s/peer": "^2", "other": "*"}
	p.PeerDependenciesMeta["@s/peer"] = lockfile.PeerMeta{Optional: true}
	p.Bin = map[string]string{"": "", "tool": "bin/tool.js"}
	g.Packages[p.DepPath] = p
	g.Importers["."] = []lockfile.DirectDep{{Name: "foo", DepPath: p.DepPath, Type: lockfile.Production}}
	got, err := EncodeBerry(g, pj)
	want := `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 10
  cacheKey: 10c0

"foo@npm:^1":
  version: 1.2.0
  resolution: "foo@npm:1.2.0"
  peerDependencies:
    "@s/peer": ^2
    other: "*"
  peerDependenciesMeta:
    "@s/peer":
      optional: true
  bin:
    tool: bin/tool.js
  checksum: 10c0/abc
  languageName: node
  linkType: hard

"project@workspace:.":
  version: 0.0.0-use.local
  resolution: "project@workspace:."
  dependencies:
    foo: "npm:~1"
  languageName: unknown
  linkType: soft
`
	if err != nil || string(got) != want {
		t.Fatalf("%v\n%s", err, got)
	}
}
func TestBerryWriterPatchPriorityAndAtomicRefusal(t *testing.T) {
	pj, _ := manifest.ParsePackage([]byte(`{"dependencies":{"foo":"patch:foo@1#./p.patch"}}`))
	g := lockfile.NewGraph()
	p := lockfile.NewPackage("foo", "1.2.0")
	g.Packages[p.DepPath] = p
	g.PatchedDependencies = map[string]string{"foo@^1": "./p.patch"}
	g.Importers["."] = []lockfile.DirectDep{{Name: "foo", DepPath: p.DepPath}}
	got, err := EncodeBerry(g, pj)
	if err != nil || !strings.Contains(string(got), "  resolution: \"foo@patch:foo@1#./p.patch\"\n") {
		t.Fatal(string(got), err)
	}
	path := filepath.Join(t.TempDir(), "yarn.lock")
	if err := os.WriteFile(path, []byte("untouched"), 0600); err != nil {
		t.Fatal(err)
	}
	g.PatchedDependencies = map[string]string{"foo@^1": "a", "foo@>=1 <2": "b"}
	if err := WriteBerry(path, g, pj); err == nil {
		t.Fatal("conflicting patch ranges accepted")
	}
	data, err := os.ReadFile(path)
	if err != nil || string(data) != "untouched" {
		t.Fatal(string(data), err)
	}
}
func TestBerryQuotingAndLocalSources(t *testing.T) {
	for _, tc := range []struct{ in, want string }{
		{"@scope/a", `"@scope/a"`}, {"^1", "^1"}, {">=1", `">=1"`}, {"npm:1", `"npm:1"`}, {`a\"b`, `a\"b`}, {"a #x", `"a #x"`},
	} {
		if got := berryQuoteIfNeeded(tc.in); got != tc.want {
			t.Fatal(tc, got)
		}
	}
	pj, _ := manifest.ParsePackage([]byte(`{}`))
	g := lockfile.NewGraph()
	p := lockfile.NewPackage("local", "1.0.0")
	p.Source = &lockfile.Source{Kind: lockfile.Portal, Path: `./a\"b`}
	p.DepPath = p.Source.DepPath(p.Name)
	g.Packages[p.DepPath] = p
	got, err := EncodeBerry(g, pj)
	if err != nil || !strings.Contains(string(got), "  linkType: soft\n") || !strings.Contains(string(got), berryQuote(p.Name+"@"+p.Source.Specifier())) {
		t.Fatal(string(got), err)
	}
}
