package yarn

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nubjs/nub/pm-go/internal/lockfile"
	"github.com/nubjs/nub/pm-go/internal/manifest"
)

func TestClassicWriterGroupsRangesAndScopedDependencies(t *testing.T) {
	data := `a@^1:
  version "1.0.0"
  integrity hash
  dependencies:
    "@s/b" "^2"
"@s/b@^2", "@s/b@~2":
  version "2.0.0"
`
	pj, _ := manifest.ParsePackage([]byte(`{"dependencies":{"a":"^1","@s/b":"~2"}}`))
	g, _, err := ParseClassic("yarn.lock", []byte(data), pj, Options{})
	if err != nil {
		t.Fatal(err)
	}
	out, err := EncodeClassic(g, pj)
	if err != nil {
		t.Fatal(err)
	}
	want := "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n\"@s/b@2.0.0\", \"@s/b@^2\", \"@s/b@~2\":\n  version \"2.0.0\"\n\n\"a@1.0.0\", \"a@^1\":\n  version \"1.0.0\"\n  integrity hash\n  dependencies:\n    \"@s/b\" \"^2\"\n\n"
	if string(out) != want {
		t.Fatal(string(out))
	}
	reparsed, _, err := ParseClassic("yarn.lock", out, pj, Options{})
	if err != nil || len(reparsed.RootDeps()) != 2 || reparsed.Packages["a@1.0.0"].Dependencies["@s/b"] != "2.0.0" {
		t.Fatal(reparsed, err)
	}
}
func TestClassicWriterKeepsLocalDescriptorsAndGitDeclaration(t *testing.T) {
	g := lockfile.NewGraph()
	p := lockfile.NewPackage("local", "0.0.0")
	p.Source = &lockfile.Source{Kind: lockfile.Directory, Path: "vendor"}
	p.DepPath = p.Source.DepPath(p.Name)
	sri := "hash"
	p.Integrity = &sri
	g.Packages[p.DepPath] = p
	g.Importers["."] = []lockfile.DirectDep{{Name: p.Name, DepPath: p.DepPath}}
	pj, _ := manifest.ParsePackage([]byte(`{"dependencies":{"local":"file:./vendor"}}`))
	out, err := EncodeClassic(g, pj)
	if err != nil || !strings.Contains(string(out), "\"local@file:./vendor\":\n  version \"0.0.0\"\n") || strings.Contains(string(out), "integrity") {
		t.Fatal(string(out), err)
	}
	git := lockfile.NewPackage("gitpkg", "1.0.0")
	git.Source = &lockfile.Source{Kind: lockfile.Git, URL: "https://github.com/o/r.git", Resolved: strings.Repeat("a", 40)}
	git.DepPath = git.Source.DepPath(git.Name)
	g.Packages[git.DepPath] = git
	if _, err := EncodeClassic(g, pj); err == nil || !strings.Contains(err.Error(), "original specifier could not be recovered") {
		t.Fatal(err)
	}
	pj.Dependencies["gitpkg"] = "github:o/r#tag"
	out, err = EncodeClassic(g, pj)
	if err != nil || !strings.Contains(string(out), "\"gitpkg@github:o/r#tag\":\n  version \"1.0.0\"\n  resolved \"https://codeload.github.com/o/r/tar.gz/"+strings.Repeat("a", 40)+"\"") {
		t.Fatal(string(out), err)
	}
	pj.Dependencies["gitpkg"] = "git+https://github.com/o/r.git#tag"
	out, err = EncodeClassic(g, pj)
	if err != nil || !strings.Contains(string(out), "  resolved \"git+https://github.com/o/r.git#tag\"") {
		t.Fatal(string(out), err)
	}
}
func TestClassicWriterFailureKeepsExistingFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "yarn.lock")
	original := []byte("existing\n")
	if err := os.WriteFile(path, original, 0600); err != nil {
		t.Fatal(err)
	}
	g := lockfile.NewGraph()
	p := lockfile.NewPackage("git", "1")
	p.Source = &lockfile.Source{Kind: lockfile.Git, URL: "https://example/repo.git", Resolved: "abc"}
	g.Packages[p.DepPath] = p
	pj, _ := manifest.ParsePackage([]byte(`{}`))
	if err := WriteClassic(path, g, pj); err == nil {
		t.Fatal("missing git descriptor accepted")
	}
	data, err := os.ReadFile(path)
	if err != nil || string(data) != string(original) {
		t.Fatal(string(data), err)
	}
}
