package yarn

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nubjs/nub/pm-go/internal/fsutil"
	"github.com/nubjs/nub/pm-go/internal/lockfile"
	"github.com/nubjs/nub/pm-go/internal/manifest"
)

// WriteClassic is the reference conversion writer. Existing Yarn classic
// projects are read-only in normal install dispatch; PM identity conversion
// may explicitly select this writer.
func WriteClassic(path string, g *lockfile.Graph, project *manifest.Package) error {
	data, err := EncodeClassic(g, project)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return fsutil.WriteDefault(path, data)
}
func EncodeClassic(g *lockfile.Graph, project *manifest.Package) ([]byte, error) {
	canonical := g.CanonicalPackages()
	extra := map[string]lockfile.Set{}
	addSpec := func(key, spec string) {
		if canonical[key] != nil && key != spec {
			if extra[key] == nil {
				extra[key] = lockfile.Set{}
			}
			extra[key].Add(spec)
		}
	}
	for _, dep := range g.RootDeps() {
		key := lockfile.CanonicalKey(dep.DepPath)
		if canonical[key] == nil {
			continue
		}
		for _, section := range []map[string]string{project.Dependencies, project.DevDependencies, project.OptionalDependencies, project.PeerDependencies} {
			if r, ok := section[dep.Name]; ok {
				addSpec(key, dep.Name+"@"+r)
				break
			}
		}
	}
	for _, key := range sortedKeys(canonical) {
		p := canonical[key]
		for _, name := range sortedKeys(p.DeclaredDependencies) {
			if value, ok := p.Dependencies[name]; ok {
				addSpec(lockfile.ChildCanonicalKey(name, value), name+"@"+p.DeclaredDependencies[name])
			}
		}
	}
	localRanges, gitRanges := map[string]string{}, map[string]string{}
	note := func(name, r string) {
		if strings.HasPrefix(r, "file:") || strings.HasPrefix(r, "link:") || strings.HasPrefix(r, "portal:") {
			if _, ok := localRanges[name]; !ok {
				localRanges[name] = r
			}
		}
		if _, ok := lockfile.ParseGit(r); ok {
			if _, exists := gitRanges[name]; !exists {
				gitRanges[name] = r
			}
		}
	}
	for _, section := range []map[string]string{project.Dependencies, project.DevDependencies, project.OptionalDependencies} {
		for _, name := range sortedKeys(section) {
			note(name, section[name])
		}
	}
	for _, key := range sortedKeys(canonical) {
		p := canonical[key]
		for _, name := range sortedKeys(p.DeclaredDependencies) {
			note(name, p.DeclaredDependencies[name])
		}
	}
	var out strings.Builder
	out.WriteString("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n")
	for _, key := range sortedKeys(canonical) {
		p := canonical[key]
		header := key
		var git *lockfile.Source
		if p.Source != nil {
			if p.Source.Kind == lockfile.Git {
				git = p.Source
			} else if hosted, ok := p.Source.HostedGitSource(); ok {
				git = hosted
			}
		}
		var gitURL *string
		if git != nil {
			rangeText, ok := gitRanges[p.Name]
			if !ok {
				return nil, fmt.Errorf("dependency `%s` is a git dependency whose original specifier could not be recovered from package.json, so it can't be written to a yarn v1 lockfile that yarn would accept. Declare it in package.json (e.g. `\"%s\": \"<owner>/<repo>#<ref>\"`) before migrating to yarn.", p.Name, p.Name)
			}
			header = p.Name + "@" + rangeText
			gitURL = gitResolved(git, rangeText)
		} else if p.Source != nil {
			rangeText, ok := localRanges[p.Name]
			if !ok {
				rangeText = p.Source.Specifier()
			}
			header = p.Name + "@" + rangeText
		}
		fmt.Fprintf(&out, "\"%s\"", header)
		for _, spec := range extra[key].Sorted() {
			fmt.Fprintf(&out, ", \"%s\"", spec)
		}
		fmt.Fprintf(&out, ":\n  version \"%s\"\n", p.Version)
		if gitURL != nil {
			fmt.Fprintf(&out, "  resolved \"%s\"\n", *gitURL)
		} else if p.Source == nil && p.Integrity != nil {
			fmt.Fprintf(&out, "  integrity %s\n", *p.Integrity)
		}
		deps := map[string]string{}
		for _, name := range sortedKeys(p.Dependencies) {
			tail := p.Dependencies[name]
			if canonical[lockfile.ChildCanonicalKey(name, tail)] == nil {
				continue
			}
			r, ok := p.DeclaredDependencies[name]
			if !ok {
				r = lockfile.DependencyVersion(name, tail)
			}
			deps[name] = r
		}
		if len(deps) != 0 {
			out.WriteString("  dependencies:\n")
			for _, name := range sortedKeys(deps) {
				key := name
				if strings.HasPrefix(key, "@") {
					key = "\"" + key + "\""
				}
				fmt.Fprintf(&out, "    %s \"%s\"\n", key, deps[name])
			}
		}
		out.WriteByte('\n')
	}
	return []byte(out.String()), nil
}
func gitResolved(git *lockfile.Source, declared string) *string {
	if git.Resolved == "" {
		return nil
	}
	urlForm := strings.HasPrefix(declared, "git+") || strings.HasPrefix(declared, "git://") || strings.HasPrefix(declared, "git@") || strings.HasPrefix(declared, "ssh://") || (strings.HasPrefix(declared, "http://") || strings.HasPrefix(declared, "https://")) && strings.Contains(declared, ".git")
	if urlForm {
		return &declared
	}
	if hosted, ok := lockfile.ParseHostedGit(git.URL); ok {
		if tarball, ok := hosted.TarballURL(git.Resolved); ok {
			return &tarball
		}
	}
	resolved := strings.TrimPrefix(git.URL, "git+") + "#" + git.Resolved
	return &resolved
}
